# Travis CI continuous integration configuration file

language: python
python:
  - "3.8"

before_install:
  # install Just
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - export PATH="$HOME/.cargo/bin:$PATH"
  - cargo install just

  # for codecoverage on codeclimate.com
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - just checkup
  - just benchmarks
  - just _build-doc

after_script:
  # for codecoverage on codeclimate.com
  - ./cc-test-reporter after-build -t coverage.py --exit-code $TRAVIS_TEST_RESULT

env:
  global:
    # for codecoverage on codeclimate.com
    - CC_TEST_REPORTER_ID=495554b5189c33d77f3404148524a617700107caa4fb990963753099aa3fc86c
