steps:
  - name: Test & publish code coverage
    uses: paambaati/codeclimate-action@v3.0.0
    env:
      CC_TEST_REPORTER_ID: 495554b5189c33d77f3404148524a617700107caa4fb990963753099aa3fc86c
    with:
      coverageCommand: coverage
      debug: true