# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install just
      uses: extractions/setup-just@v1
    - name: Install poetry
      uses: abatilo/actions-poetry@v2
    - name: Install dependencies
      run: |
        just install
    - name: Lint with flake8, mypy, pylint, isort and black
      run: |
        just lint
    - name: Test with pytest
      run: |
        just cov
    - name: Test & publish code coverage
      # https://github.com/marketplace/actions/code-climate-coverage-action
      uses: paambaati/codeclimate-action@v3.0.0
      env:
        CC_TEST_REPORTER_ID: 495554b5189c33d77f3404148524a617700107caa4fb990963753099aa3fc86c
