name: Pages
on:
  push:
    branches:
    - main
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v4
    - uses: actions/checkout@main
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Install just
      uses: extractions/setup-just@v1
    - name: Install poetry
      uses: abatilo/actions-poetry@v2
    - name: Install dependencies
      run: just install
    - name: Build and Commit
      uses: sphinx-notes/pages@v3
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages